#!/bin/bash
coverage run -m unittest discover -s tests/
coverage report
coverage xml
curl -Os https://uploader.codecov.io/latest/macos/codecov
chmod +x codecov
./codecov -t 1acd659b-39c1-4296-8d0d-55cabf3d2f38
